const config = require('../config/config');

const BREEDER_BEHAVIOUR_TYPE = {
    home_page: 'home-page',
    verify: 'verify',
};

const BREED_BEHAVIOUR_TYPE = {
    premium: 'is_premium',
    available: 'is_available',
    rare: 'is_rare',
};

/** All modules of HappyPet(this) project */
const HAPPY_PET_MODULES = {
    blog: 'Blog',
    breed: 'Breed',
    event: 'Event',
    pet_shelter_n_rescue: 'Pet shelter & rescue',
    pet_store: 'Pet store',
    blog_topic: 'Blog topic',
    pet_influencer: 'Pet influencer',
    pet_startup: 'Pet startup',
    knowledge_center: 'Knowledge center',
};

const ALL_BREED_SIZE = {
    nano: 'Nano',
    small: 'Small',
    medium: 'Medium',
    large: 'Large',
    giant: 'Giant',
    monster: 'Monster',
};

const DOG_PREDEFINED = {
    AVOID_INGREDIENTS: {
        alcohol: 'Alcohol',
        almonds: 'Almonds',
        avocados: 'Avocados',
        cherries: 'Cherries',
        cinnamon: 'Cinnamon',
        chocolate: 'Chocolate',
        coffee_or_Tea: 'Coffee / Tea',
        dairy: 'Dairy',
        fruit_seed: 'Fruit seeds',
        garlic: 'Garlic',
        grapes: 'Grapes',
        lemon: 'Lemon',
        milk_products: 'Milk Products',
        mushrooms: 'Mushrooms',
        onions: 'Onions',
        salt: 'Salt',
        sugar: 'Sugar',
        xylitol: 'Xylitol',
    },
    BREEDS: {
        akita: 'Akita',
        alaskan_malamute: 'Alaskan Malamute',
        australian_cattle_dog: 'Australian Cattle Dog',
        american_bulldog: 'American Bulldog',
        american_staffordshire_terrier: 'American Staffordshire Terrier',
        bakharwal_dog: 'Bakharwal dog',
        basset_hound: 'Basset Hound',
        beagle: 'Beagle',
        belgian_malinois: 'Belgian Malinois',
        belgian_shepherd: 'Belgian Shepherd',
        boerboel: 'Boerboel',
        border_collie: 'Border Collie',
        borzoi: 'Borzoi',
        boxer: 'Boxer',
        bull_dog: 'Bull Dog',
        bull_mastiff: 'Bull Mastiff',
        bully_kutta: 'Bully Kutta',
        caucasian_shepherd_dog: 'Caucasian Shepherd Dog',
        cavalier_king_charles_spaniel: 'Cavalier King Charles Spaniel',
        chihuahua: 'Chihuahua',
        chippiparai: 'Chippiparai',
        dalmatian: 'Dalmatian',
        doberman_pinscher: 'Doberman Pinscher',
        dutch_shepherd: 'Dutch Shepherd',
        english_cocker_spaniel: 'English Cocker Spaniel',
        french_bulldog: 'French Bulldog',
        french_mastiff: 'French Mastiff',
        gaddi_kutta: 'Gaddi Kutta',
        german_shepherd: 'German Shepherd',
        german_spitz: 'German Spitz',
        golden_retriever: 'Golden Retriever',
        great_dane: 'Great Dane',
        greyhound: 'Greyhound',
        gull_dong: 'Gull Dong',
        husky: 'Husky',
        indian_pariah_dog: 'Indian Pariah Dog',
        indian_spitz: 'Indian Spitz',
        kaikadi: 'Kaikadi',
        kombai_or_combai_dog: 'Kombai or Combai Dog',
        kumaon_mastiff: 'Kumaon Mastiff',
        labrador_retriever: 'Labrador Retriever',
        mahratta_greyhound: 'Mahratta Greyhound',
        mudhol_hound: 'Mudhol hound',
        pandikona: 'Pandikona',
        pomeranian: 'Pomeranian',
        poodle: 'Poodle',
        pug: 'Pug',
        rajapalayam: 'Rajapalayam',
        rhodesian_ridgeback: 'Rhodesian Ridgeback',
        rottweiler: 'Rottweiler',
        jack_russel_terrier: 'Jack Russel Terrier',
        saint_bernard: 'Saint Bernard',
        sarplaninac: 'Sarplaninac',
        shih_tzu: 'Shih - Tzu',
        siberian_husky: 'Siberian Husky',
        south_russian_shepherd_dog: 'South Russian Shepherd Dog',
        tibetan_mastiff: 'Tibetan Mastiff',
        affenpinscher: 'Affenpinscher',
        afghan_hound: 'Afghan Hound',
        akbash: 'Akbash',
        american_bully: 'American Bully',
        american_eskimo_dog: 'American Eskimo Dog',
        american_pit_bull_terrier: 'American Pit Bull Terrier',
        american_cocker_spaniel: 'American Cocker Spaniel',
        australian_kelpie: 'Australian Kelpie',
        azawakh: 'Azawakh',
        barbet: 'Barbet',
        basenji: 'Basenji',
        bernese_mountain_dog: 'Bernese Mountain Dog',
        black_mouth_cur: 'Black Mouth Cur',
        bichon_frise: 'Bichon Frise',
        biewer_terrier: 'Biewer Terrier',
        bull_terrier: 'Bull Terrier',
        brittany: 'Brittany',
        canaan_dog: 'Canaan Dog',
        cane_corso: 'Cane Corso',
        carolina_dog: 'Carolina Dog',
        catahoula_leopard_dog: 'Catahoula Leopard Dog',
        central_asian_shepherd_dog: 'Central Asian Shepherd Dog',
        cesky_terrier: 'Cesky Terrier',
        chesapeake_bay_retriever: 'Chesapeake Bay Retriever',
        chinese_crested: 'Chinese Crested',
        chinese_shar_pe: 'Chinese Shar-Pe',
        chinook: 'Chinook',
        chow_chow: 'Chow Chow',
        cocker_spaniel: 'Cocker Spaniel',
        croatian_sheepdog: 'Croatian Sheepdog',
        czechoslovakian_vlcak: 'Czechoslovakian Vlcak',
        dachshund: 'Dachshund',
        dandie_dinmont_terrier: 'Dandie Dinmont Terrier',
        danish_swedish_farmdog: 'Danish-Swedish Farmdog',
        deutscher_wachtelhund: 'Deutscher Wachtelhund',
        drever: 'Drever',
        dogo_argentino: 'Dogo Argentino',
        dogue_de_bordeaux: 'Dogue de Bordeaux',
        drentsche_patrijshond: 'Drentsche Patrijshond',
        english_foxhound: 'English Foxhound',
        english_setter: 'English Setter',
        english_springer_spaniel: 'English Springer Spaniel',
        english_toy_spaniel: 'English Toy Spaniel',
        entlebucher_mountain_dog: 'Entlebucher Mountain Dog',
        estrela_mountain_dog: 'Estrela Mountain Dog',
        eurasier: 'Eurasier',
        field_spaniel: 'Field Spaniel',
        fila_brasileiro: 'Fila Brasileiro',
        finnish_lapphund: 'Finnish Lapphund',
        finnish_spitz: 'Finnish Spitz',
        fox_terrier: 'Fox Terrier',
        french_spaniel: 'French Spaniel',
        german_longhaired_pointer: 'German Longhaired Pointer',
        german_pinscher: 'German Pinscher',
        german_shorthaired_pointer: 'German Shorthaired Pointer',
        german_wirehaired_pointer: 'German Wirehaired Pointer',
        giant_schnauzer: 'Giant Schnauzer',
        glen_of_imaal_terrier: 'Glen of Imaal Terrier',
        greater_swiss_mountain_dog: 'Greater Swiss Mountain Dog',
        great_pyrenees: 'Great Pyrenees',
        hamiltonstovare: 'Hamiltonstovare',
        hanoverian_scenthound: 'Hanoverian Scenthound',
        harrier: 'Harrier',
        havanese: 'Havanese',
        hokkaido: 'Hokkaido',
        hovawart: 'Hovawart',
        ibizan_hound: 'Ibizan Hound',
        icelandic_sheepdog: 'Icelandic Sheepdog',
        irish_red_and_white_setter: 'Irish Red And White Setter',
        irish_setter: 'Irish Setter',
        irish_terrier: 'Irish Terrier',
        irish_water_spaniel: 'Irish Water Spaniel',
        irish_wolfhound: 'Irish Wolfhound',
        italian_greyhound: 'Italian Greyhound',
        jagdterrier: 'Jagdterrier',
        japanese_chin: 'Japanese Chin',
        japanese_spitz: 'Japanese Spitz',
        kai_ken: 'Kai Ken',
        kangal_shepherd_dog: 'Kangal Shepherd Dog',
        karelian_bear_dog: 'Karelian Bear Dog',
        keeshond: 'Keeshond',
        kerry_blue_terrier: 'Kerry Blue Terrier',
        kishu_ken: 'Kishu Ken',
        komondor: 'Komondor',
        kooikerhondje: 'Kooikerhondje',
        korean_jindo_dog: 'Korean Jindo Dog',
        kromfohrlander: 'Kromfohrlander',
        kuvasz: 'Kuvasz',
        lagotto_romagnolo: 'Lagotto Romagnolo',
        lakeland_terrier: 'Lakeland Terrier',
        lancashire_heeler: 'Lancashire Heeler',
        lapponian_herder: 'Lapponian Herder',
        leonberger: 'Leonberger',
        lhasa_apso: 'Lhasa Apso',
        lowchen: 'Lowchen',
        maltese: 'Maltese',
        manchester_terrier: 'Manchester Terrier',
        maremma_sheepdog: 'Maremma Sheepdog',
        mastiff: 'Mastiff',
        miniature_pinscher: 'Miniature Pinscher',
        miniature_schnauzer: 'Miniature Schnauzer',
        moscow_guard: 'Moscow Guard',
        mountain_cur: 'Mountain Cur',
        mountain_feist: 'Mountain Feist',
        mudi: 'Mudi',
        neapolitan_mastiff: 'Neapolitan Mastiff',
        newfoundland: 'Newfoundland',
        norfolk_terrier: 'Norfolk Terrier',
        norwegian_buhund: 'Norwegian Buhund',
        norwegian_elkhound: 'Norwegian Elkhound',
        norwegian_lundehund: 'Norwegian Lundehund',
        norwich_terrier: 'Norwich Terrier',
        nova_scotia_duck_tolling_retriever: 'Nova Scotia Duck Tolling Retriever',
        old_english_sheepdog: 'Old English Sheepdog',
        otterhound: 'Otterhound',
        papillon: 'Papillon',
        patterdale_terrier: 'Patterdale Terrier',
        pekingese: 'Pekingese',
        perro_de_presa_canario: 'Perro de Presa Canario',
        petit_basset_griffon_venden: 'Petit Basset Griffon Vendéen',
        pharaoh_hound: 'Pharaoh Hound',
        plott: 'Plott',
        pointer: 'Pointer',
        polish_lowland_sheepdog: 'Polish Lowland Sheepdog',
        portuguese_podengo_pequeno: 'Portuguese Podengo Pequeno',
        portuguese_pointer: 'Portuguese Pointer',
        portuguese_sheepdog: 'Portuguese Sheepdog',
        portuguese_water_dog: 'Portuguese Water Dog',
        pudelpointer: 'Pudelpointer',
        puli: 'Puli',
        pyrenean_mastiff: 'Pyrenean Mastiff',
        pyrenean_shepherd: 'Pyrenean Shepherd',
        rafeiro_do_alentejo: 'Rafeiro do Alentejo',
        rat_terrier: 'Rat Terrier',
        redbone_coonhound: 'Redbone Coonhound',
        romanian_mioritic_shepherd_dog: 'Romanian Mioritic Shepherd Dog',
        russian_toy: 'Russian Toy',
        russian_tsvetnaya_bolonka: 'Russian Tsvetnaya Bolonka',
        saluki: 'Saluki',
        samoyed: 'Samoyed',
        schapendoes: 'Schapendoes',
        schipperke: 'Schipperke',
        scottish_deerhound: 'Scottish Deerhound',
        scottish_terrier: 'Scottish Terrier',
        sealyham_terrier: 'Sealyham Terrier',
        segugio_italiano: 'Segugio Italiano',
        shetland_sheepdog: 'Shetland Sheepdog',
        shiba_inu: 'Shiba Inu',
        shikoku: 'Shikoku',
        shiloh_shepherd: 'Shiloh Shepherd',
        silken_windhound: 'Silken Windhound',
        silky_terrier: 'Silky Terrier',
        skye_terrier: 'Skye Terrier',
        sloughi: 'Sloughi',
        slovakian_wirehaired_pointer: 'Slovakian Wirehaired Pointer',
        slovensky_cuvac: 'Slovensky Cuvac',
        slovensky_kopov: 'Slovensky Kopov',
        small_munsterlander_pointer: 'Small Munsterlander Pointer',
        soft_coated_wheaten_terrier: 'Soft Coated Wheaten Terrier',
        spanish_mastiff: 'Spanish Mastiff',
        spanish_water_dog: 'Spanish Water Dog',
        spinone_italiano: 'Spinone Italiano',
        stabyhoun: 'Stabyhoun',
        staffordshire_bull_terrier: 'Staffordshire Bull Terrier',
        standard_schnauzer: 'Standard Schnauzer',
        sussex_spaniel: 'Sussex Spaniel',
        swedish_lapphund: 'Swedish Lapphund',
        swedish_vallhund: 'Swedish Vallhund',
        taiwan_dog: 'Taiwan Dog',
        thai_ridgeback: 'Thai Ridgeback',
        tibetan_spaniel: 'Tibetan Spaniel',
        tibetan_terrier: 'Tibetan Terrier',
        tornjak: 'Tornjak',
        tosa: 'Tosa',
        tosa_inu: 'Tosa Inu',
        toy_fox_terrier: 'Toy Fox Terrier',
        transylvanian_hound: 'Transylvanian Hound',
        treeing_tennessee_brindle: 'Treeing Tennessee Brindle',
        treeing_walker_coonhound: 'Treeing Walker Coonhound',
        vizsla: 'Vizsla',
        weimaraner: 'Weimaraner',
        welsh_corgi: 'Welsh Corgi',
        welsh_springer_spaniel: 'Welsh Springer Spaniel',
        welsh_terrier: 'Welsh Terrier',
        west_highland_white_terrier: 'West Highland White Terrier',
        whippet: 'Whippet',
        wirehaired_pointing_griffon: 'Wirehaired Pointing Griffon',
        wolf_dog: 'Wolf Dog',
        working_kelpie: 'Working Kelpie',
        xiasi: 'Xiasi',
        xoloitzcuintli: 'Xoloitzcuintli',
        yakutian_laika: 'Yakutian Laika',
        yorkshire_terrier: 'Yorkshire Terrier',
        urinary_tract_infections: 'Urinary Tract Infections (UTI)',
    },
    COMMON_HEALTH_ISSUES: {
        blastomycosis: 'Blastomycosis',
        bloat: 'Bloat',
        canine_distemper: 'Canine distemper',
        canine_influenza: 'Canine Influenza',
        heartworm: 'Heartworm',
        hip_dysplasia: 'Hip Dysplasia',
        kennel_cough: 'Kennel Cough',
        leptospirosis: 'Leptospirosis',
        lyme_disease: 'Lyme disease',
        panosteitis: 'Panosteitis',
        parasites: 'Parasites',
        parvovirus: 'Parvovirus',
        rabies: 'Rabies',
        ringworm: 'Ringworm',
        skin_fold_dermatitis: 'Skin Fold Dermatitis',
        patellar_luxation: 'Patellar Luxation',
        epilepsy: 'Epilepsy',
        skin_allergies: 'Skin Allergies',
        progressive_retinal_atrophy: 'Progressive Retinal Atrophy (PRA)',
        cancer: 'Cancer',
        allergies: 'Allergies',
        ear_infections: 'Ear Infections',
        heart_disease: 'Heart Disease',
        thyroid_disease: 'Thyroid Disease',
        elbow_dysplasia: 'Elbow dysplasia',
        von_willebrands_disease: "Von Willebrand's Disease",
        eye_disorders: 'Eye Disorders',
        eye_problems: 'Eye problems',
        autoimmune_disorders: 'Autoimmune Disorders',
        hereditary_necrotizing_myelopathy: 'Hereditary necrotizing myelopathy',
    },
    CHARACTERISTICS: {
        barking: 'Barking',
        temperament_with_kids: 'Temperament with Kids',
        playfulness: 'Playfulness',
        friendliness: 'Friendliness',
        compatibility_with_other_dogs: 'Compatibility with other dogs',
    },
    DOCUMENTS_FOR_ADOPTION: {
        identification_proof: 'Identification proof',
        address_proof: 'Address Proof',
        noc: 'NOC',
        pet_registration: 'Pet Registration',
        vaccination_records: 'Vaccination records',
        purchase_agreement: 'Purchase Agreement',
    },
    ESSENTIAL_NUTRIENTS: {
        carbohydrates: 'Carbohydrates',
        fats: 'Fats',
        minerals: 'Minerals',
        omega3: 'Omega3',
        protein: 'Protein',
        vitamins: 'Vitamins',
        fibre: 'Fibre',
    },
    FOODS: {
        chicken: 'Chicken',
        dry_dog_food: 'Dry Dog Food',
        fresh_meat: 'Fresh Meat',
        fresh_fish: 'Fresh Fish',
        fruits: 'Fruits',
        mutton: 'Mutton',
        home_made_meals: 'Home made meals',
        vegetables: 'Vegetables',
    },
    GROUPS: {
        herding: 'Herding',
        hound: 'Hound',
        non_sporting: 'Non-Sporting',
        sporting: 'Sporting',
        terrier: 'Terrier',
        toy: 'Toy',
        working: 'Working',
        utility: 'Utility',
        primitive: 'Primitive',
        spitz: 'Spitz',
        companion: 'Companion',
    },
    HYGEINE_CHECKLIST: {
        bathing: 'Bathing',
        brushing: 'Brushing',
        ear_cleaning: 'Ear Cleaning',
        eye_care: 'Eye Care',
        nail_trimming: 'Nail Trimming',
        teeth_care: 'Teeth Care',
    },
    PROCESS_FOR_ADOPTION: {
        fill_application: 'Fill Application',
        home_visit_by_agencies: 'Home Visit by agencies',
        reference_letters: 'Reference Letters',
        adoption_fee: 'Adoption Fee',
    },
    PREREQUISITES: {
        access_to_groomer: 'Access to Groomer',
        access_to_veterinary: 'Access to Veterinary',
        appropriate_climate: 'Appropriate Climate',
        lifestyle_compatibility: 'Lifestyle Compatibility',
        financial_capability: 'Financial Capability',
        space_and_environment: 'Space and Environment',
        willingness_to_train: 'Willingness to train',
        time_and_effort: 'Time and Effort',
    },
    RECOGNISING_STRESS: {
        changes_in_appetite: 'Changes in appetite',
        excessive_barking: 'Excessive Barking',
        pacing: 'Pacing',
        excessive_panting: 'Excessive Panting',
        reluctance_to_move: 'Reluctance to move',
        increased_laziness: 'Increased laziness',
        decreased_play: 'Decreased play',
    },
    SIZE: {
        small: 'Small',
        medium: 'Medium',
        large: 'Large',
        giant: 'Giant',
    },
    BREED_SIZE_WITH_IMG: [
        {
            name: 'Small',
            image: `${config.base_url}/default/small_dog.png`,
        },
        {
            name: 'Medium',
            image: `${config.base_url}/default/medium_dog.png`,
        },
        {
            name: 'Large',
            image: `${config.base_url}/default/large_dog.png`,
        },
        {
            name: 'Giant',
            image: `${config.base_url}/default/giant_dog.png`,
        },
    ],
    TRAITS: {
        aggressive: 'Aggressive',
        athletic: 'Athletic',
        disciplined: 'Disciplined',
        energetic: 'Energetic',
        fearless: 'Fearless',
        intelligent: 'Intelligent',
        lazy: 'Lazy',
        loyal: 'Loyal',
        playful: 'Playful',
        protective: 'Protective',
        affectionate: 'Affectionate',
        friendly: 'Friendly',
    },
    WELLBEING: {
        exercise: 'Exercise',
        agility_training: 'Agility Training',
        bonding: 'Bonding',
        games: 'Games',
        socialization: 'Socialization',
        hiking: 'Hiking',
    },
};

const LIFE_TIME_PERIOD = {
    years: 'years',
    months: 'months',
    days: 'days',
};

const MAINTENANCE = {
    low: 'Low',
    moderate: 'Moderate',
    high: 'High',
};

const IDEAL_SPACE = {
    apartment: 'Apartment',
    independent_house: 'Independent House',
    house_with_backyard: 'House with backyard',
    house_with_farm_area: 'House with Farm Area',
};

const WEATHER_TYPE = {
    celsius: 'celsius',
    fahrenheit: 'fahrenheit',
    kelvin: 'kelvin',
};

const TIME_DURATION = {
    minutes: 'minutes',
    hours: 'hours',
};

const ENERGY_LEVEL = {
    very_low: 'Very Low',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    very_high: 'Very High',
};

const BENEFITS_OF_GROOMING = {
    cleanliness: 'Cleanliness',
    low_shedding: 'Low Shedding',
    odourless: 'Odourless',
    prevents_bad_breath: 'Prevents Bad Breath',
    prevents_infections: 'Prevents infections',
    quality_of_life: 'Quality of life',
};
const SHEDDING = {
    no_shedding: 'No Shedding',
    low_shedding: 'Low Shedding',
    moderate_shedding: 'Moderate Shedding',
    high_shedding: 'High Shedding',
    very_high_shedding: 'Very High Shedding',
};

const CAT_PREDEFINED = {
    BREEDS: {
        bombay_cat: 'Bombay Cat',
        himalayan_cat: 'Himalayan Cat',
        siamese_cat: 'Siamese Cat',
        rusty_spotted_cat: 'Rusty-Spotted Cat',
        ragdoll_cat: 'Ragdoll Cat',
        birman_cat: 'Birman Cat',
        abyssinian: 'Abyssinian',
        oriental_shorthair: 'Oriental Shorthair',
        tonkinese_cat: 'Tonkinese Cat',
        persian_cat: 'Persian Cat',
        maine_coon: 'Maine Coon',
        american_bobtail: 'American Bobtail',
        bengal_cat: 'Bengal Cat',
        sphynx_cat: 'Sphynx Cat',
        turkish_van: 'Turkish Van',
        chartreux_cat: 'Chartreux Cat',
        burmese_cat: 'Burmese Cat',
        british_shorthair_cat: 'British Shorthair Cat',
        korat_cat: 'Korat Cat',
        aegean: 'Aegean',
        american_curl: 'American Curl',
        american_ringtail: 'American Ringtail',
        american_shorthair: 'American Shorthair',
        american_wirehair: 'American Wirehair',
        aphrodite_giant: 'Aphrodite Giant',
        arabian_mau: 'Arabian Mau',
        asian_semi_longhair: 'Asian Semi-longhair',
        australian_Mist: 'Australian Mist',
        balinese_cat: 'Balinese Cat',
        bambino: 'Bambino',
        brazilian_shorthair: 'Brazilian Shorthair',
        british_longhair: 'British Longhair',
        burmilla: 'Burmilla',
        california_spangled: 'California Spangled',
        chantilly_tiffany: 'Chantilly Tiffany',
        chausie: 'Chausie',
        colorpoint_shorthair: 'Colorpoint Shorthair',
        cornish_rex: 'Cornish Rex',
        cymric: 'Cymric',
        cyprus: 'Cyprus',
        devon_rex: 'Devon Rex',
        dragon_li: 'Dragon Li',
        dwelf: 'Dwelf',
        egyptian_mau: 'Egyptian Mau',
        european_shorthair: 'European Shorthair',
        exotic_shorthair: 'Exotic Shorthair',
        foldex: 'Foldex',
        german_rex: 'German Rex',
        havana_brown: 'Havana Brown',
        highlander: 'Highlander',
        japanese_Bobtail: 'Japanese Bobtail',
        javanese_or_colorpoint_longhair: 'Javanese or Colorpoint Longhair',
        selkirk_rex: 'Selkirk Rex',
        serengeti: 'Serengeti',
        serrade_petit: 'Serrade Petit',
        siberian: 'Siberian',
        singapura: 'Singapura',
        snowshoe: 'Snowshoe',
        sokoke: 'Sokoke',
        somali: 'Somali',
        suphalak: 'Suphalak',
        toybob: 'Toybob',
        toyger: 'Toyger',
        turkish_angora: 'Turkish Angora',
        ukrainian_levkoy: 'Ukrainian Levkoy',
        york_chocolate: 'York Chocolate',
        balinese: 'Balinese',
        cheetoh: 'Cheetoh',
        donskoy: 'Donskoy',
        javanese: 'Javanese',
        khao_manee: 'Khao Manee',
        la_perm: 'LaPerm',
        manx: 'Manx',
        munchkin: 'Munchkin',
        nebelung: 'Nebelung',
        norwegian_forest: 'Norwegian Forest',
        ocicat: 'Ocicat',
        pixie_bob: 'Pixie-Bob',
        raas_cat: 'Raas cat',
        russian_white_cat: 'Russian White Cat',
        sam_sawet: 'Sam Sawet',
        russian_blue: 'Russian Blue',
        scottish_fold: 'Scottish fold',
    },
    TRAITS: {
        playful: 'Playful',
        curious: 'Curious',
        friendly: 'Friendly',
        independent: 'Independent',
        affectionate: 'Affectionate',
        shy: 'Shy',
        vocal: 'Vocal',
        territorial: 'Territorial',
        timid: 'Timid',
        laid_back: 'Laid-back',
        active: 'Active',
        aloof: 'Aloof',
        mischievous: 'Mischievous',
        aggressive: 'Aggressive (rare, but possible)',
        nervous: 'Nervous',
        calm: 'Calm',
        reserved: 'Reserved',
        cautious: 'Cautious',
        energetic: 'Energetic',
        gentle: 'Gentle',
    },
    ESSENTIAL_NUTRIENTS: {
        protein: 'Protein',
        fats: 'Fats',
        carbohydrates: 'Carbohydrates',
        vitamins: 'Vitamins',
        minerals: 'Minerals',
        water: 'Water',
        amino_acids: 'Amino Acids (Taurine, Arginine, etc.)',
        essential_fatty_acids: 'Essential Fatty Acids',
        fiber: 'Fiber',
    },
    SIZE: {
        small: 'Small',
        medium: 'Medium',
        large: 'Large',
    },
    FOODS: {
        dry_kibble: 'Dry kibble',
        wet_canned_food: 'Wet canned food',
        semi_moist_cat_food: 'Semi-moist cat food',
        chicken_cooked_or_raw: 'Chicken (cooked or raw)',
        turkey: 'Turkey',
        lamb: 'Lamb',
        beef_in_moderation: 'Beef (in moderation)',
        salmon: 'Salmon',
        tuna: 'Tuna',
        mackerel: 'Mackerel',
        sardines_in_moderation: 'Sardines (in moderation)',
        eggs_cooked: 'Eggs (cooked)',
        cottage_cheese: 'Cottage cheese',
        tofu_in_moderation: 'Tofu (in moderation)',
        rice_cooked: 'Rice (cooked)',
        pasta_plain_without_sauces: 'Pasta (plain, without sauces)',
        oatmeal_cooked: 'Oatmeal (cooked)',
        pumpkin: 'Pumpkin',
        carrots_cooked: 'Carrots (cooked)',
        sweet_potatoes_cooked: 'Sweet potatoes (cooked)',
        peas_cooked: 'Peas (cooked)',
        apples_remove_seeds: 'Apples (remove seeds)',
        blueberries: 'Blueberries',
        watermelon: 'Watermelon',
        bananas: 'Bananas',
        plain_yogurt_no_added_sugar: 'Plain yogurt (no added sugar)',
        cheese_small_amounts: 'Cheese (small amounts)',
        milk_lactose_free: 'Milk (lactose-free)',
        cat_specific_multivitamins: 'Cat-specific multivitamins',
        omega_3_fatty_acids: 'Omega-3 fatty acids',
    },
    AVOID_INGREDIENTS: {
        onions_and_garlic: 'Onions and Garlic',
        caffeine: 'Caffeine',
        chocolate: 'Chocolate',
        alcohol: 'Alcohol',
        bones: 'Bones',
        raw_eggs: 'Raw Eggs',
        dairy_in_some_cases: 'Dairy (in some cases)',
        grapes_and_raisins: 'Grapes and Raisins',
        xylitol: 'Xylitol',
        artificial_sweeteners: 'Artificial Sweeteners',
        high_salt_foods: 'High Salt Foods',
        high_fat_foods: 'High-Fat Foods',
        moldy_or_spoiled_food: 'Moldy or Spoiled Food',
        dog_food: 'Dog Food',
        plants_and_flowers: 'Plants and Flowers',
        artificial_additives: 'Artificial Additives',
    },
    COMMON_HEALTH_ISSUES: {
        upper_respiratory_infections: 'Upper Respiratory Infections',
        dental_problems: 'Dental Problems',
        obesity: 'Obesity',
        diabetes: 'Diabetes',
        kidney_disease: 'Kidney Disease',
        hyperthyroidism: 'Hyperthyroidism',
        heartworm_disease: 'Heartworm Disease',
        fleas_and_ticks: 'Fleas and Ticks',
        hairballs: 'Hairballs',
        gastrointestinal_issues: 'Gastrointestinal Issues',
        urinary_tract_infections: 'Urinary Tract Infections (UTI)',
        feline_immunodeficiency_virus_fiv: 'Feline Immunodeficiency Virus (FIV)',
        feline_leukemia_virus_felv: 'Feline Leukemia Virus (FeLV)',
        arthritis: 'Arthritis',
        skin_allergies: 'Skin Allergies',
        eye_problems: 'Eye Problems',
        pancreatitis: 'Pancreatitis',
        bladder_stones: 'Bladder Stones',
        hypertension_high_blood_pressure: 'Hypertension (High Blood Pressure)',
        cancer: 'Cancer',
        behavioral_issues: 'Behavioral Issues',
        skin__coat_disorders: 'Skin & coat disorders',
        polycystic_kidney_disease: 'Polycystic Kidney Disease',
        progressive_retinal_atrophy: 'Progressive Retinal Atrophy',
        gastroenteritis: 'Gastroenteritis',
        otitis_externa_ear_inflammation: 'Otitis Externa (Ear Inflammation)',
        dental_resorption_lesions: 'Dental Resorption Lesions',
        fatty_liver_disease_hepatic_lipidosis: 'Fatty Liver Disease (Hepatic Lipidosis)',
        constipation: 'Constipation',
        sepsis: 'Sepsis',
        eosinophilic_granuloma_complex_egc: 'Eosinophilic Granuloma Complex (EGC)',
        thromboembolism_blood_clots: 'Thromboembolism (Blood Clots)',
        anemia: 'Anemia',
        diarrhea: 'Diarrhea',
        cataracts: 'Cataracts',
        retinal_disorders: 'Retinal Disorders',
        chronic_renal_failure_crf: 'Chronic Renal Failure (CRF)',
        peritonitis: 'Peritonitis',
        bladder_cancer: 'Bladder Cancer',
        pyelonephritis_kidney_infection: 'Pyelonephritis (Kidney Infection)',
        nasal_polyps: 'Nasal Polyps',
        hypertrophic_cardiomyopathy_hcm: 'Hypertrophic Cardiomyopathy (HCM)',
        ringworm: 'Ringworm',
        conjunctivitis: 'Conjunctivitis',
        stomatitis: 'Stomatitis',
        hematuria_blood_in_urine: 'Hematuria (Blood in Urine)',
        dental_malocclusion: 'Dental Malocclusion',
        mammary_gland_tumors: 'Mammary Gland Tumors',
        nasopharyngeal_polyps: 'Nasopharyngeal Polyps',
        lymphoma: 'Lymphoma',
        gastric_dilatation_volvulus_gdv: 'Gastric Dilatation-Volvulus (GDV)',
        megacolon: 'Megacolon',
        feline_acne: 'Feline Acne',
        urolithiasis_urinary_stones: 'Urolithiasis (Urinary Stones)',
        feline_infectious_peritonitis_fip: 'Feline Infectious Peritonitis (FIP)',
        patellar_luxation: 'Patellar Luxation',
    },
    ACTIVITIES: {
        play_with_toys: 'Play with Toys',
        chasing_objects: 'Chasing Objects',
        exploring: 'Exploring',
        climbing: 'Climbing',
        scratching: 'Scratching',
        hunting_games: 'Hunting Games',
        interactive_feeders: 'Interactive Feeders',
        hide_and_seek: 'Hide and Seek',
        sunbathing: 'Sunbathing',
        watching_birds: 'Watching Birds',
        grooming: 'Grooming',
        napping: 'Napping',
        social_interaction: 'Social Interaction',
        lounging: 'Lounging',
        hiding_places: 'Hiding Places',
        interactive_playtime: 'Interactive Playtime',
        catnip_play: 'Catnip Play',
        water_play: 'Water Play',
        socializing_with_other_cats: 'Socializing with Other Cats',
    },
    RECOGNISING_STRESS: {
        hiding: 'Hiding',
        increased_vocalization: 'Increased vocalization',
        decreased_appetite: 'Decreased appetite',
        overgrooming: 'Overgrooming',
        changes_in_litter_box_behavior: 'Changes in litter box behavior',
        diarrhea: 'Diarrhea',
        vomiting: 'Vomiting',
        restlessness: 'Restlessness',
        aggression: 'Aggression',
        lethargy: 'Lethargy',
        pacing: 'Pacing',
        excessive_meowing: 'Excessive meowing',
        dilated_pupils: 'Dilated pupils',
        tail_twitching: 'Tail twitching',
        scratching_furniture_or_walls: 'Scratching furniture or walls',
        avoiding_eye_contact: 'Avoiding eye contact',
        increased_aggression_towards_other_pets: 'Increased aggression towards other pets',
        excessive_sleeping: 'Excessive sleeping',
        changes_in_body_posture: 'Changes in body posture',
        reduced_playfulness: 'Reduced playfulness',
        changes_in_social_behavior: 'Changes in social behavior',
        excessive_shedding: 'Excessive shedding',
        changes_in_appetite: 'Changes in appetite',
        compulsive_behaviors:
            'Compulsive behaviors (e.g., excessive grooming, licking, or chewing)',
        increased_sensitivity_to_noise_or_movement: 'Increased sensitivity to noise or movement',
        unusual_body_odor: 'Unusual body odor',
        hiding_in_elevated_locations: 'Hiding in elevated locations',
        purring_or_vocalizing_in_a_distressed_manner:
            'Purring or vocalizing in a distressed manner',
        scratching_or_biting_themselves: 'Scratching or biting themselves',
        changes_in_sleeping_patterns:
            'Changes in sleeping patterns (e.g., insomnia or sleeping more than usual)',
        avoidance_of_certain_people_or_areas: 'Avoidance of certain people or areas',
        startling_easily: 'Startling easily',
        excessive_salivation_or_drooling: 'Excessive salivation or drooling',
        changes_in_body_weight_either_gain_or_loss: 'Changes in body weight (either gain or loss)',
        agitation: 'Agitation',
        clinginess: 'Clinginess',
        attempts_to_escape: 'Attempts to escape',
        changes_in_drinking_behavior: 'Changes in drinking behavior',
        uncharacteristic_aggression_towards_humans: 'Uncharacteristic aggression towards humans',
        tail_tucked_between_legs: 'Tail tucked between legs',
        avoidance_of_eye_contact: 'Avoidance of eye contact',
        increased_vigilance: 'Increased vigilance',
        fecal_accidents_outside_the_litter_box: 'Fecal accidents outside the litter box',
        changes_in_vocalization_patterns: 'Changes in vocalization patterns',
        scratching_or_biting_at_themselves: 'Scratching or biting at themselves',
        piloerection_raising_of_fur: 'Piloerection (raising of fur)',
        excessive_yawning: 'Excessive yawning',
        urinating_in_unusual_places: 'Urinating in unusual places',
        changes_in_territorial_behavior: 'Changes in territorial behavior',
        submissive_behavior: 'Submissive behavior',
    },
    HYGEINE_CHECKLIST: {
        feeding: 'Feeding',
        litter_box: 'Litter Box',
        grooming_for_some_breeds: 'Grooming (for some breeds)',
        hydration: 'Hydration',
        play_and_exercise: 'Play and Exercise',
        health_observation: 'Health Observation',
        worming_if_needed: 'Worming (if needed)',
        nail_trimming: 'Nail Trimming',
        anal_gland_expression: 'Anal Gland Expression',
        fur_trimming: 'Fur trimming',
        bathing: 'Bathing',
        ear_cleaning: 'Ear cleaning',
        teeth_care: 'Teeth care',
        eye_care: 'Eye care',
    },
};

const FISH_PREDEFINED = {
    BREEDS: {
        betta_fish: 'Betta Fish',
        arulius_barb: 'Aruilus Barb',
        filament_barb: 'Filament Barb',
        odessa_barb: 'Odessa Barb',
        honey_gourami: 'Honey Gourami',
        flagfin_angelfish: 'Flagfin Anglefish',
        chocolate_tang: 'Chocolate Tang',
        platinum_arowana: 'Platinum arowana',
        gold_fish: 'Gold Fish',
        guppy: 'Guppy',
        zebrafish: 'Zebrafish',
        chalk_bass: 'Chalk Bass',
    },
    SIZE: {
        nano: 'Nano',
        small: 'Small',
        medium: 'Medium',
        large: 'Large',
        monster: 'Monster',
    },
    CARE_AND_EXPERTISE: {
        beginner: 'Beginner',
        intermediate: 'Intermediate',
        advanced: 'Advanced',
        professional: 'Professional',
        scientist: 'Scientist',
    },
    // TRAITS: {
    //     aggressive: 'Aggressive',
    //     adaptable: 'Adaptable',
    //     active: 'Active',
    //     curious: 'Curious',
    //     fairly_intelligent: 'Fairly Intelligent',
    // },
    // ESSENTIAL_NUTRIENTS: {
    //     proteins: 'Proteins',
    //     vitamins: 'Vitamins',
    //     amino_acids: 'Amino Acids',
    // },
    // FOODS: {
    //     betta_pellets: 'Betta Pellets',
    //     betta_flakes: 'Betta Flakes',
    //     bloodworms: 'Bloodworms',
    //     brine_shrimp: 'Brine Shrimp',
    //     mysis_shrimp: 'Mysis Shrimp',
    //     tubifex_worms: 'Tubifex Worms',
    //     mosquito_larvae: 'Mosquito Larvae',
    // },
    // AVOID_INGREDIENTS: {
    //     fatty_meat: 'Fatty Meat',
    //     crunchy_greens: 'Crunchy Greens',
    //     bread: 'Bread',
    //     crackers: 'Crackers',
    //     dog_food: 'Dog Food',
    // },
    COMMON_HEALTH_ISSUES: {
        fin_rot: 'Fin rot',
        pop_eye: 'Pop eye (swollen eyes)',
        color_dimming: 'Color dimming',
        white_spot: 'White spot / ick',
        anchor_worm: 'Anchor worm',
        fungus: 'Fungus',
        dropsy: 'Dropsy (swollen abdomen)',
        carp_pox: 'Carp pox',
        velvet: 'Velvet',
        columnaris: 'Columnaris (cotton wool-like growth on the skin)',
        ammonia_poisoning: 'Ammonia poisoning',
        scale_protrusion: 'Scale protrusion',
        parasites: 'Parasites',
        swim_bladder_inflammation: 'Swim bladder inflammation',
        bacterial_infections: 'Bacterial infections',
        viral_infections: 'Viral infections',
        senile_changes: 'Senile changes',
        ich: 'Ich (white spot disease)',
        velvet_disease: 'Velvet disease (yellowish-brown spots on the skin)',
        swim_bladder_disease: 'Swim bladder disease',
        hole_in_the_head_disease: 'Hole in the head disease',
        mouth_fungus: 'Mouth fungus',
        gill_disease: 'Gill disease',
        parasitic_infections: 'Parasitic infections',
        fungal_infections: 'Fungal infections',
    },
    SIGN_OF_GOOD_HEALTH: {
        active: 'Active',
        bright_coloration: 'Bright coloration',
        good_apetite: 'Good apetite',
        undamaged_fins: 'Undamaged fins',
    },
    SIGN_OF_SICKNESS: {
        loss_of_appetite: 'Loss of appetite',
        lethargic_behaviour: 'Lethargic behaviour',
        frequently_hiding: 'Frequent hiding ',
        dull_coloring: 'Dull coloring',
        tattered_fins: 'Tattered fins ',
        white_growths: 'White growths',
        swimming_abnormally: 'Swimming abnormally',
        white_film: 'White film',
        cloudy_eyes: 'Cloudy eyes',
        hemorrhaging: 'Hemorrhaging',
        lack_of_appetite: 'Lack of appetite',
        spitting_out_food: 'Spitting out food',
        reduced_activity: 'Reduced activity',
        increased_breathing_rate: 'Increased breathing rate',
        loss_of_balance: 'Loss of balance',
        long_stringy_white_feces: 'Long, stringy white feces',
        swollen_abdomen: 'Swollen abdomen',
        yellowish_brown_spots_on_skin: 'Yellowish-brown spots on the skin',
        cotton_wool_like_growth_on_skin: 'Cotton wool-like growth on the skin',
        swim_bladder_issues: 'Swim bladder issues',
        hole_in_head: 'Hole in the head',
        mouth_fungus: 'Mouth fungus',
        swollen_eyes: 'Swollen eyes',
        gill_disease: 'Gill disease',
        scratching_against_objects: 'Scratching against objects',
        layer_of_mucus: 'Layer of mucus',
        chewed_on_or_eaten_away_gills_or_fins: 'Chewed on or eaten-away gills or fins',
        reddened_skin: 'Reddened skin',
        hemorrhaging_of_internal_organs: 'Hemorrhaging of internal organs, skin, and muscle',
        bloated_abdomens: 'Bloated abdomens',
        open_sores: 'Open sores',
        progressive_deterioration: 'Progressive deterioration',
        fins_become_frayed: 'Fins become frayed or their color may fade',
        necrosis_and_ulcer: 'Necrosis and ulcer on different body parts',
        black_coloration: 'Black coloration',
        erratic_swimming: 'Erratic swimming',
    },
    PREREQUISITES: {
        adequate_tank_space: 'Adequate tank space',
        cleanliness: 'Cleanliness',
        effort_n_commitment: 'Effort & commitment',
        enriching_environment: 'Enriching Environment',
        financial_capability: 'Financial Capability',
    },
    // ADOPTION_PROCESS: {
    //     fill_application: 'Fill Application',
    //     home_visit_by_agencies: 'Home Visit by agencies',
    //     reference_letters: 'Reference Letters',
    //     adoption_fee: 'Adoption Fee',
    // },
    ESSENTIAL_EQUIPMENTS: {
        aquarium_tank: 'Aquarium tank',
        water_filter: 'Water filter',
        heater: 'Heater',
        light: 'Light',
        substrate: 'Substrate',
        decor: 'Decor',
    },
    // COMPATIBLE_MATES: {
    //     cory_catfish: 'Cory Catfish',
    //     harlequin_rasboras: 'Harlequin Rasboras',
    //     ember_tetras: 'Ember Tetras',
    //     neon_tetras: 'Neon Tetras',
    //     clown_pleco: 'Clown Pleco',
    // },
    WATER_TYPE: {
        fresh_water: 'Fresh Water',
        salt_water: 'Salt Water',
        brackish: 'Brackish',
    },
    MEASUREMENT_TYPES: {
        mm: 'mm',
        cm: 'cm',
        inches: 'inches',
        feet: 'feet',
        meters: 'meters',
    },
    DIET: {
        herbivore: 'Herbivore',
        carnivore: 'Carnivore',
        omnivore: 'Omnivore',
    },
};

const BIRD_PREDEFINED = {
    SIZE: {
        small: 'Small',
        medium: 'Medium',
        large: 'Large',
    },
    TRAITS: {
        friendly: 'Friendly',
        talkative: 'Talkative',
        playful: 'Playful',
        shy: 'Shy',
        curious: 'Curious',
        intelligent: 'Intelligent',
        social: 'Social',
        independent: 'Independent',
        aggressive: 'Aggressive',
        gentle: 'Gentle',
        affectionate: 'Affectionate',
        quiet: 'Quiet',
        energetic: 'Energetic',
    },
    ESSENTIAL_NUTRIENTS: {
        protein: 'Protein',
        carbohydrates: 'Carbohydrates',
        fats: 'Fats',
        vitamins: 'Vitamins',
        minerals: 'Minerals',
        lipids: 'Lipids',
    },
    FOODS: {
        seeds: 'Seeds',
        nuts: 'Nuts',
        fruits: 'Fruits',
        vegetables: 'Vegetables',
        grasses: 'Grasses',
        herbs: 'Herbs',
        cooked_eggs: 'Cooked eggs',
        yoghurt: 'Yoghurt (Small amounts)',
        legumes: 'Legumes',
        tofu: 'Tofu',
        whole_grain_breads: 'Whole grain breads',
        low_or_non_fat_cheese: 'Low or non-fat cheese',
        peanut_butter: 'Peanut butter (Small amounts)',
        lean_cooked_meat: 'Lean cooked meat',
        fish: 'Fish',
        cheese: 'Cheese (in very small amounts)',
        pinky_mice: 'Pinky mice (for Mynah birds)',
        leafy_greens: 'Leafy Greens',
        pasta: 'Pasta',
        rice: 'Rice',
        beans: 'Beans',
        sprouts: 'Sprouts',
        pellets: 'Pellets',
    },
    AVOID_INGREDIENTS: {
        dairy_products: 'Dairy products',
        high_fat_foods: 'High-fat foods',
        mushrooms: 'Mushrooms',
        onions: 'Onions',
        garlic: 'Garlic',
        grit: 'Grit',
        salty_snacks: 'Salty snacks',
        fish: 'Fish',
        tomatoes: 'Tomatoes (leaves and stems)',
        uncooked_beans: 'Uncooked beans',
        xylitol: 'Xylitol',
        seafood: 'Seafood',
        honey: 'Honey',
        avocado: 'Avocado',
        aubergine: 'Aubergine',
        nutmeg: 'Nutmeg',
        chocolate: 'Chocolate',
        caffeine: 'Caffeine',
        alcohol: 'Alcohol',
        raw_beans: 'Raw beans',
    },
    COMMON_HEALTH_ISSUES: {
        psittacosis: 'Psittacosis',
        respiratory_infections: 'Respiratory Infections',
        fatty_liver_disease: 'Fatty liver disease',
        reproductive_problems: 'Reproductive problems',
        feather_cysts: 'Feather cysts',
        chlamydiosis: 'Chlamydiosis',
        gastrointestinal_tract_yeast_infections: 'Gastrointestinal tract yeast infections',
        infectious_causes_of_feather_loss: 'Infectious causes of feather loss',
        proventricular_dilatation_disease: 'Proventricular Dilatation Disease (PDD)',
        psittacine_beak_and_feather_disease: 'Psittacine Beak and Feather Disease (PBFD)',
        polyomavirus: 'Polyomavirus',
        pachecos_herpesvirus: "Pacheco's Herpesvirus (Pacheco's Disease)",
        other_herpesvirus_infections: 'Other Herpesvirus Infections',
        poxvirus_infections: 'Poxvirus Infections',
        mycobacteriosis: 'Mycobacteriosis (Avian Tuberculosis)',
        poisoning_from_fumes_and_aerosols: 'Poisoning from fumes and aerosols',
        feather_plucking: 'Feather Plucking',
        avian_bornavirus: 'Avian Bornavirus (Proventricular Dilatation Disease, PDD)',
        aspergillosis: 'Aspergillosis',
        candidiasis: 'Candidiasis',
        egg_binding: 'Egg Binding',
        gout: 'Gout',
        bumblefoot: 'Bumblefoot (Pododermatitis)',
        parasitic_infections: 'Parasitic Infections (e.g., mites, lice)',
        sour_crop: 'Sour Crop (Crop Stasis)',
        heavy_metal_toxicity: 'Heavy Metal Toxicity (Lead and Zinc Poisoning)',
        nutritional_deficiencies: 'Nutritional Deficiencies (e.g., Vitamin A deficiency)',
        fatty_liver_disease_hepatic_lipidosis: 'Fatty Liver Disease (Hepatic Lipidosis)',
        avian_gastric_yeast: 'Avian Gastric Yeast (Macrorhabdus ornithogaster)',
        newcastle_disease: 'Newcastle Disease',
        pachecos_disease: "Pacheco's Disease",
        beak_malocclusion: 'Beak Malocclusion',
        cloacal_prolapse: 'Cloacal Prolapse',
        conjunctivitis: 'Conjunctivitis',
        arthritis: 'Arthritis',
        egg_yolk_peritonitis: 'Egg Yolk Peritonitis',
        heat_stress: 'Heat Stress',
        kidney_disease: 'Kidney Disease',
        tapeworms: 'Tapeworms (Cestodes)',
        crop_burns: 'Crop Burns',
        pigeon_paramyxovirus: 'Pigeon Paramyxovirus (PPMV)',
        pigeon_fungal_infections: 'Pigeon Fungal Infections',
        pigeon_malaria: 'Pigeon Malaria',
        wing_and_leg_injuries: 'Wing and Leg Injuries',
    },
    CLASSIFICATION: {
        psittaciformes: 'Psittaciformes',
        passeriformes: 'Passeriformes',
        columbiformes: 'Columbiformes',
        anseriformes: 'Anseriformes',
        galliformes: 'Galliformes',
    },
    ESSENTIAL_EQUIPMENTS: {
        bird_cage: 'Bird Cage',
        cage_stand: 'Cage Stand',
        cage_cover: 'Cage Cover',
        perches: 'Perches',
        food_water_dishes: 'Food/ water dishes',
        toys_and_enrichment: 'Toys and Enrichment',
        cage_liner_paper: 'Cage Liner Paper',
        newspaper: 'Newspaper',
        bird_cage_bedding: 'Bird Cage Bedding',
        cuttle_bone: 'Cuttle Bone',
        mineral_block: 'Mineral Block',
        grit: 'Grit',
        bird_bath: 'Bird Bath',
        shower_perch: 'Shower Perch',
        cage_cleaning_brush: 'Cage Cleaning Brush',
    },
    RECOGNISING_STRESS: {
        feather_plucking: 'Feather Plucking',
        tail_bobbing: 'Tail Bobbing',
        excessive_vocalization: 'Excessive Vocalization',
        aggression: 'Aggression',
        withdrawal_or_hiding: 'Withdrawal or Hiding',
        loss_of_appetite: 'Loss of Appetite',
        repetitive_movements: 'Repetitive Movements',
        decreased_social_interaction: 'Decreased Social Interaction',
        hyperactivity: 'Hyperactivity',
        fearful_reactions: 'Fearful Reactions',
        changes_in_sleep_patterns: 'Changes in Sleep Patterns',
        head_shaking_or_tilting: 'Head Shaking or Tilting',
        self_mutilation: 'Self-Mutilation',
        regurgitation: 'Regurgitation',
        excessive_preening: 'Excessive Preening',
        weight_loss: 'Weight Loss',
        fluffed_up_feathers: 'Fluffed Up Feathers',
        changes_in_droppings: 'Changes in Droppings',
        panting_or_open_mouth_breathing: 'Panting or Open-Mouth Breathing',
        stress_bars_on_feathers: 'Stress Bars on Feathers',
        eye_pinning: 'Eye Pinning',
        swollen_or_red_eyes: 'Swollen or Red Eyes',
        nasal_discharge: 'Nasal Discharge',
        weakness_or_lethargy: 'Weakness or Lethargy',
        trembling_or_shaking: 'Trembling or Shaking',
        feather_cysts: 'Feather Cysts',
        dry_flaky_skin: 'Dry, Flaky Skin',
        bald_patches: 'Bald Patches',
        obesity: 'Obesity',
        overgrowth_of_beak_and_nails: 'Overgrowth of beak and nails',
        egg_binding: 'Egg-binding',
        chronic_egg_laying: 'Chronic egg-laying',
        tumors: 'Tumors',
    },
    PREVENTATIVE_MEASURES: {
        physical_checkup_every_6_12_months: 'Physical checkup every 6-12 months',
        annual_blood_work: 'Annual Blood Work',
        annual_fecal_exam: 'Annual Fecal Exam',
        beak_assessment: 'Beak Assessment',
        nail_trimming: 'Nail Trimming',
        feather_assessment: 'Feather Assessment',
        // dental_exam: 'Dental Exam',
        environmental_enrichment: 'Environmental Enrichment',
        avoid_sudden_diet_changes: 'Avoid Sudden Diet Changes',
        use_cage_covers: 'Use Cage Covers',
        mental_stimulation: 'Mental Stimulation',
        physical_stimulation: 'Physical Stimulation',
    },
};

const ENQUIRY = {
    puppy_enquiry: 'Puppy Enquiry',
    general_enquiry: 'General Enquiry',
    pet_influencer_enquiry: 'Pet Influencer Enquiry',
};

const FILES_FOLDER = {
    public: 'public',
    temp: 'temp',
    userImages: 'userImages',
    userProfileImages: 'userProfileImages',
    userShowOffImages: 'userShowOffImages',
    adminImages: 'adminImages',
    productImage: 'productImage',
    categoryImage: 'categoryImage',
    breedFiles: 'breedFiles',
    bannerImages: 'bannerImages',
    galleryImages: 'galleryImages',
    breedVariants: 'breedVariants',
    breedCoatVariants: 'breedCoatVariants',
    popularBreedImages: 'popularBreedImages',
    blogsImages: 'blogsImages',
    authorImages: 'authorImages',
    kennelCertificate: 'kennelCertificate',
    dogImages: 'dogImages',
    dogGalleryImages: 'dogGalleryImages',
    dogAwardImages: 'dogAwardImages',
    dogDocumentImages: 'dogDocumentImages',
    puppyImages: 'puppyImages',
    reviewImages: 'reviewImages',
    csv: 'csv',
    psrImages: 'psrImages',
    logoImage: 'logoImage',
    eventImages: 'eventImages',
    petStoreImages: 'petStoreImages',
    seoImages: 'seoImages',
    webPageSeoImages: 'webPageSeoImages',
    breedSeoImages: 'breedSeoImages',
    blogSeoImages: 'blogSeoImages',
    eventSeoImages: 'eventSeoImages',
    psrSeoImages: 'psrSeoImages',
    petStoreSeoImages: 'petStoreSeoImages',
    parentsPet: 'parentsPet',
    petInfluencerImages: 'petInfluencerImages',
    influencerImage: 'influencerImage',
    blogTopicSeoImages: 'blogTopicSeoImages',
    petInfluencerSeoImages: 'petInfluencerSeoImages',
    petStartupSeoImages: 'petStartupSeoImages',
    petParentImages: 'petParentImages',
    petImage: 'petImage',
    petDocument: 'petDocument',
    petStartupImages: 'petStartupImages',
    peopleImages: 'peopleImages',
    dairyImages: 'dairyImages',
    knowledgeCenterSeoImages: 'knowledgeCenterSeoImages',
    editorImages: 'editorImages',
    headerImages: 'headerImages',
    broadcastNotificationImages: 'broadcastNotificationImages',
};

const FILE_QUALITY = {
    large: { type: 'large', quality: 80 },
    small: { type: 'small', quality: 1 },
};

const PET_TYPE = {
    cat: 'cat',
    dog: 'dog',
    fish: 'fish',
    bird: 'bird',
};

const ROLES = {
    super_admin: 'super_admin',
    user: 'user',
    sub_admin: 'sub_admin',
    breeder: 'breeder',
    pet_parent: 'pet_parent',
};

const SOCIAL_TYPES = {
    apple: 'apple',
    google: 'google',
    facebook: 'facebook',
};

const TOKEN_TYPES = {
    ACCESS: 'access',
    RESET_PASSWORD: 'resetPassword',
    VERIFY_OTP: 'verify_otp',
};

const SOCKET_EVENT_TYPE = {
    CONNECT: 'connect',
    CONNECT_USER: 'connect-user',
    JOIN: 'join',
    STATUS: 'status',
    LEAVE: 'leave',
    SEND_MESSAGE: 'send-message',
    UNREAD_MESSAGE: 'unread-message',
    READ_MESSAGE: 'read-message',
    DISCONNECT_USER: 'disconnect-user',
    DISCONNECT: 'disconnect',
    REMOVE_CONNECTION: 'remove-connection',
    CONNECT_INDICATOR: 'connect-indicator',
    REQ_STATUS: 'req-status',
    SEND_REQUEST: 'send-request',
    DELETE_ACCOUNT: 'delete-account',
};

const MESSAGE_ACTION_TYPE = {
    reconnect: 'reconnect',
    remove: 'remove',
    accept: 'accept',
    reject: 'reject',
};

const WEIGHT_TYPES = {
    KGS: 'kgs',
    LBS: 'lbs',
    grams: 'grams',
};

const BLOG_TOPICS = [
    { slug: 'business-and-innovations', topic: 'Business and Innovations' },
    { slug: 'pet-startups', topic: 'Pet Startups' },
    { slug: 'businesses', topic: 'Businesses' },
    { slug: 'artificial-intelligence', topic: 'Artificial Intelligence' },
    { slug: 'latest-product-launch', topic: 'Latest Product Launch' },
    { slug: 'grooming', topic: 'Grooming' },
    { slug: 'pet-supplies', topic: 'Pet Supplies' },
    { slug: 'mobile-application', topic: 'Mobile Application' },
    { slug: 'investments', topic: 'Investments' },
    { slug: 'health-and-tips', topic: 'Health and Tips' },
    { slug: 'pet-product', topic: 'Pet Product' },
    { slug: 'pet-care', topic: 'Pet Care' },
    { slug: 'pet-tech', topic: 'Pet tech' },
    { slug: 'funding', topic: 'Funding' },
    { slug: 'pet-parenting', topic: 'Pet-Parenting' },
    { slug: 'pawsitively-purrfect-pets', topic: 'Pawsitively Purrfect Pets' },
    { slug: 'the-pet-project', topic: 'The Pet Project' },
    { slug: 'furry-friends-inc', topic: 'Furry Friends Inc.' },
    { slug: 'critter-comforts', topic: 'Critter Comforts' },
    { slug: 'pets-gone-wild', topic: 'Pets Gone Wild' },
    { slug: 'pet-tech-today', topic: 'Pet Tech Today' },
    { slug: 'animal-innovation', topic: 'Animal Innovation' },
    { slug: 'the-future-of-pets', topic: 'The Future of Pets' },
    { slug: 'pet-friendly-world', topic: 'Pet-Friendly World' },
    { slug: 'pet-trends-to-watch', topic: 'Pet Trends to Watch' },
    { slug: 'pampered-pets', topic: 'Pampered Pets' },
    { slug: 'the-groom-room', topic: 'The Groom Room' },
    { slug: 'the-dog-washery', topic: 'The Dog Washery' },
    { slug: 'clip-n-clean', topic: "Clip 'n' Clean" },
    { slug: 'the-furry-salon', topic: 'The Furry Salon' },
    { slug: 'pet-spa', topic: 'Pet Spa' },
    { slug: 'pawdicures-and-purrfumes', topic: 'Pawdicures & Purrfumes' },
    { slug: 'the-dog-house', topic: 'The Dog House' },
    { slug: 'the-cats-meow', topic: "The Cat's Meow" },
    { slug: 'all-creatures-great-and-small', topic: 'All Creatures Great & Small' },
    { slug: 'the-pet-parlor', topic: 'The Pet Parlor' },
    { slug: 'pet-supplies', topic: 'Pet Supplies' },
    { slug: 'the-pet-pantry', topic: 'The Pet Pantry' },
    { slug: 'the-barkery', topic: 'The Barkery' },
    { slug: 'pet-paradise', topic: 'Pet Paradise' },
    { slug: 'all-things-pet', topic: 'All Things Pet' },
    { slug: 'pet-central', topic: 'Pet Central' },
    { slug: 'pet-supplies-plus', topic: 'Pet Supplies Plus' },
    { slug: 'pet-food-and-more', topic: 'Pet Food & More' },
    { slug: 'pet-toys-and-treats', topic: 'Pet Toys & Treats' },
    { slug: 'pets-and-people', topic: 'Pets & People' },
    { slug: 'your-pets-best-friend', topic: "Your Pet's Best Friend" },
    { slug: 'my-pets-place', topic: "My Pet's Place" },
    { slug: 'animals', topic: 'Animals' },
    { slug: 'furry-friends', topic: 'Furry Friends' },
    { slug: 'critters-and-companions', topic: 'Critters & Companions' },
    { slug: 'our-animal-allies', topic: 'Our Animal Allies' },
    { slug: 'pets-a-part-of-the-family', topic: 'Pets: A Part of the Family' },
    { slug: 'the-animal-kingdom', topic: 'The Animal Kingdom' },
    { slug: 'the-world-of-pets', topic: 'The World of Pets' },
    { slug: 'behavior', topic: 'Behavior' },
    { slug: 'pet-psychology', topic: 'Pet Psychology' },
    { slug: 'animal-behavior', topic: 'Animal Behavior' },
    { slug: 'pet-training-tips', topic: 'Pet Training Tips' },
    { slug: 'understanding-your-pet', topic: 'Understanding Your Pet' },
    { slug: 'pet-communication', topic: 'Pet Communication' },
    { slug: 'pet-friendly-lifestyle', topic: 'Pet-Friendly Lifestyle' },
    { slug: 'care-and-health', topic: 'Care & Health' },
    { slug: 'pet-nutrition', topic: 'Pet Nutrition' },
    { slug: 'pet-healthcare', topic: 'Pet Healthcare' },
    { slug: 'pet-safety', topic: 'Pet Safety' },
    { slug: 'pet-exercise', topic: 'Pet Exercise' },
    { slug: 'pet-aging', topic: 'Pet Aging' },
    { slug: 'fun-and-activities', topic: 'Fun & Activities' },
    { slug: 'pet-travel', topic: 'Pet Travel' },
    { slug: 'pet-photography', topic: 'Pet Photography' },
    { slug: 'pet-sports-and-games', topic: 'Pet Sports & Games' },
    { slug: 'pet-friendly-events', topic: 'Pet-Friendly Events' },
    { slug: 'pet-diy-projects', topic: 'Pet DIY Projects' },
    { slug: 'pet-friendly-recipes', topic: 'Pet-Friendly Recipes' },
    { slug: 'love-and-friendship', topic: 'Love & Friendship' },
    { slug: 'the-pet-human-bond', topic: 'The Pet-Human Bond' },
    { slug: 'pets-and-our-mental-health', topic: 'Pets & our Mental Health' },
    { slug: 'pets-and-our-emotional-well-being', topic: 'Pets & Our Emotional Well-Being' },
    { slug: 'the-power-of-pet-love', topic: 'The Power of Pet Love' },
    { slug: 'pets-make-life-better', topic: 'Pets Make Life Better' },
    { slug: 'pets-our-furry-therapists', topic: 'Pets: Our Furry Therapists' },
    { slug: 'animal-shelters', topic: 'Animal Shelters' },
    { slug: 'animal-rescue', topic: 'Animal Rescue' },
    { slug: 'adoption', topic: 'Adoption' },
    { slug: 'animal-welfare', topic: 'Animal Welfare' },
    { slug: 'dog-breeders', topic: 'Dog Breeders' },
    { slug: 'shelters-and-rescues', topic: 'Shelters & Rescues' },
];

const GENDER = {
    male: 'Male',
    female: 'Female',
    boy: 'Boy',
    girl: 'Girl',
    other: 'Other',
};

const KCI_REGISTRATION = {
    applied: 'Applied',
    have_kci: 'Have KCI',
};

const LANGUAGE = {
    english: 'English',
    hindi: 'Hindi',
    kannada: 'Kannada',
    tamil: 'Tamil',
    telugu: 'Telugu',
    marathi: 'Marathi',
    bengali: 'Bengali',
    gujarati: 'Gujarati',
    urdu: 'Urdu',
    odia: 'Odia',
    malayalam: 'Malayalam',
    punjabi: 'Punjabi',
    assamese: 'Assamese',
    bodo: 'Bodo',
    dogri: 'Dogri',
    kashmiri: 'Kashmiri',
    konkani: 'Konkani',
    maithili: 'Maithili',
    manipuri: 'Manipuri',
    nepali: 'Nepali',
    sanskrit: 'Sanskrit',
    santali: 'Santali',
    sindhi: 'Sindhi',
};

const PUPPY_STATUS = {
    active: 'Active',
    inactive: 'Inactive',
    sold: 'Sold',
};

const BLOG_PET_TYPES = {
    cat: 'Cat',
    dog: 'Dog',
    fish: 'Fish',
    bird: 'Bird',
    other_pets: 'Other Pets',
};

const PSR_PET_TYPES = {
    dog: 'Dog',
    guinea_pig: 'Guinea pig',
    horse: 'Horse',
    terrapin: 'Terrapin',
    birds: 'Bird',
    cat: 'Cat',
    buffalo: 'Buffalo',
    cow: 'Cow',
    hen: 'Hen',
    donkey: 'Donkey',
    pig: 'Pig',
    goat: 'Goat',
    rabbit: 'Rabbit',
    camel: 'Camel',
    duck: 'Duck',
    bull: 'Bull',
    cattle: 'Cattle',
    wild_life: 'Wild life',
    monkey: 'Monkey',
};

const PSR_ANIMALS = [
    {
        animal: 'Dog',
        animal_image: `${config.image_url}psrDefaultImages/dog.webp`,
    },
    {
        animal: 'Guinea pig',
        animal_image: `${config.image_url}psrDefaultImages/guinea-pig.webp`,
    },
    {
        animal: 'Horse',
        animal_image: `${config.image_url}psrDefaultImages/horse.webp`,
    },
    {
        animal: 'Terrapin',
        animal_image: `${config.image_url}psrDefaultImages/terrapin.webp`,
    },
    {
        animal: 'Bird',
        animal_image: `${config.image_url}psrDefaultImages/birds.webp`,
    },
    {
        animal: 'Cat',
        animal_image: `${config.image_url}psrDefaultImages/cats.webp`,
    },
    {
        animal: 'Buffalo',
        animal_image: `${config.image_url}psrDefaultImages/buffalo.webp`,
    },
    {
        animal: 'Cow',
        animal_image: `${config.image_url}psrDefaultImages/cow.webp`,
    },
    {
        animal: 'Hen',
        animal_image: `${config.image_url}psrDefaultImages/hen.webp`,
    },
    {
        animal: 'Donkey',
        animal_image: `${config.image_url}psrDefaultImages/donkey.webp`,
    },
    {
        animal: 'Pig',
        animal_image: `${config.image_url}psrDefaultImages/pig.webp`,
    },
    {
        animal: 'Goat',
        animal_image: `${config.image_url}psrDefaultImages/goat.webp`,
    },
    {
        animal: 'Rabbit',
        animal_image: `${config.image_url}psrDefaultImages/rabbit.webp`,
    },
    {
        animal: 'Camel',
        animal_image: `${config.image_url}psrDefaultImages/camel.webp`,
    },
    {
        animal: 'Duck',
        animal_image: `${config.image_url}psrDefaultImages/duck.webp`,
    },
    {
        animal: 'Bull',
        animal_image: `${config.image_url}psrDefaultImages/bull.webp`,
    },
    {
        animal: 'Cattle',
        animal_image: `${config.image_url}psrDefaultImages/cow.webp`,
    },
    {
        animal: 'Wild life',
        animal_image: `${config.image_url}psrDefaultImages/wild-life.webp`,
    },
    {
        animal: 'Monkey',
        animal_image: `${config.image_url}psrDefaultImages/monkey.webp`,
    },
];

// const SERVICE_PROVIDED = {
//     abc_arv_for_stray_animals: 'ABC-ARV for stray animals',
//     community_sponsored_clinic: 'Community Sponsored Clinic',
//     animal_welfare_training_center: 'Animal Welfare Training Center',
//     networking: 'Networking',
//     adoption: 'Adoption',
//     outreeach_awareness: 'Outreach Awareness',
// };

const NOTIFICATION_TYPES = {
    add_puppy: 'add_puppy',
    follow_breeder: 'follow_breeder',
    puppy_like: 'puppy_like',
    general_enquiry: 'general_enquiry',
    puppy_enquiry: 'puppy_enquiry',
};

const EVENT_TYPES = {
    trade_show: 'Trade Show',
    pet_adoption: 'Pet Adoption',
    dog_show: 'Dog Show',
    cat_show: 'Cat Show',
    community_event: 'Community Event',
    pet_show: 'Pet Show',
    conference: 'Conference',
};

const MSG91_WHATSAPP_TEMPLATES_NAME = {
    breeder_reg_done: 'breeder_reg_done', // PROD
    cust_puppy_enq_sent: 'cust_puppy_enq_sent', // PROD
    breeder_puppy_enq_received: 'breeder_puppy_enq_received', // PROD
    customer_gen_enq_sent: 'customer_gen_enq_sent', // PROD
    breeder_gen_enq_received: 'breeder_gen_enq_received', // PROD
    list_puppies_for_free: 'list_puppies_for_free', // PROD - [GUEST_USER (NOT REGISTERED BREEDER)]
    list_puppies_for_free_for_registered_breeder: 'list_puppies_for_free_for_registered_breeder', // PROD - [BREEDER]
    indias_best_breeder: 'indias_best_breeder', // PROD - [GUEST_USER (NOT REGISTERED BREEDER)]
    breeder_marketing: 'breeder_marketing', // PROD - [GUEST_USER (NOT REGISTERED BREEDER)]
    t1_sent_otp: 't1_sent_otp', // TEST
    puppy_listing_marketing_template: 'puppy_listing_marketing_template', // PROD
    puppy_listing_marketing_template_for_registered_breeders:
        'puppy_listing_marketing_template_for_registered_breeders', // PROD
    holi_message_for_breeder: 'holi_message_for_breeder', // PROD [ Guest User]
};

const MSG91_WHATSAPP_CAMPAIGN_NAME = {
    list_puppies_for_free: 'list-puppies-for-free',
    list_puppies_for_free_for_registered_breeder: 'list-puppies-for-free-for-registered-breeder',
    indias_best_breeder: 'indias-best-breeder',
    holi_message_for_breeder: 'holi-message-for-breeder',
    breeder_marketing: 'breeder-marketing',
    puppy_listing_marketing_template: 'puppy-listing-marketing-template',
    puppy_listing_marketing_template_for_registered_breeders:
        'puppy-listing-marketemp-for-registered-breeders',
};

const AI_SENSY = {
    /** List out AiSensy Champaign Name */
    CHAMPAIGN: {
        breeder_registration_complete: 'Breeder Registration Complete',
        breeder_general_enquiry_received: 'Breeder General Enquiry Received',
        customer_general_enquiry_sent: 'Customer General Enquiry Sent',
        breeder_puppy_enquiry_received: 'Breeder Puppy Enquiry Received',
        customer_puppy_enquiry_sent: 'Customer Puppy Enquiry Sent',
        pet_store_details_to_customer: 'Pet store details to customer',
        to_pet_store_about_customer: 'To pet store about the customer',
        customer_pet_influencer_enq: 'Customer Pet Influencer Enquiry',
    },
};

const PET_STORE = {
    SERVICE_PROVIDED: {
        available_for_sale: {
            pet_food: 'Pet Food',
            treats: 'Treats',
            toys: 'Toys',
            clothing: 'Clothing',
            accessories: 'Accessories',
            aquarium_accessories: 'Aquarium Accessories',
            pet_pharmaceuticals: 'Pet Pharmaceuticals',
        },
        services: {
            pet_grooming: 'Pet Grooming',
            veterinary: 'Veterinary',
            pet_boarding: 'Pet Boarding',
            in_store_shopping: 'In-Store Shopping',
            pet_shop: 'Pet Shop',
            pet_adopt: 'Pet Adopt',
            online_shopping: 'Online Shopping',
            home_delivery: 'Home Delivery',
            same_day_delivery: 'Same Day Delivery',
        },
        pets: {
            dogs: 'Dogs',
            cats: 'Cats',
            birds: 'Birds',
            aquarium_fishes: 'Aquarium Fishes',
            rabbits: 'Rabbits',
            hamsters: 'Hamsters',
        },
        payment: {
            credit_card: 'Credit Card and Debit Card',
            upi: 'UPI Payments',
            cheques: 'Cheques',
            // amex_card: 'Amex Card',
            cash: 'Cash',
            wallet_payment: 'Wallet Payment',
            net_banking: 'Net Banking',
            cod: 'Cash on Delivery',
            online_buy_now_pay_later: 'Online - Buy Now Pay Later',
        },
    },
};

const NEWSLETTER = {
    TYPES: {
        newsletter: 'Newsletter',
    },
    SUBSCRIBE_FOR: {
        all: 'all',
        news_n_stories: 'news_n_stories',
        pet_startup: 'pet_startup',
    },
};

const EVENT_FEE_TYPE = {
    free: 'Free',
    paid: 'Paid',
    not_disclosed: 'Not Disclosed',
};

const TIME_TYPES = {
    HRS: 'hrs',
    MINS: 'mins',
    SECS: 'secs',
};

const TIME_OF_DAY = {
    MORNING: 'Morning',
    AFTERNOON: 'Afternoon',
    NIGHT: 'Night',
};

const WALK_STATUS = {
    START: 'Start',
    PAUSE: 'Pause',
    FINISH: 'Finish',
    RESUME: 'Resume',
};

const MOTIVATIONS = {
    be_the_best_breeder: 'Be the best breeder',
    win_dog_shows: 'Win dog shows',
    Provide_the_healthiest_pups: 'Provide the healthiest pups',
    Breeding_purebred_dogs: 'Breeding purebred dogs',
    Ethical_breeding_practices: 'Ethical breeding practices',
    Be_a_recognised_breeder: 'Be a recognised breeder',
    Promote_good_dog_breeding_practices: 'Promote good dog breeding practices',
    The_love_of_dogs: 'The love of dogs',
    Be_a_part_of_the_breeder_community: 'Be a part of the breeder community',
};

const PET_INFLUENCER = {
    ACCOUNT_TYPES: {
        pet_influencer: 'Pet influencer',
        pet_centric_influencer: 'Pet-centric influencer',
    },
    CATEGORY: {
        adoption: 'Adoption',
        training: 'Training',
        grooming: 'Grooming',
        health_n_wellness: 'Health & Wellness',
        fashion: 'Fashion',
        travel: 'Travel',
        entertainment: 'Entertainment',
        food: 'Food',
        toys: 'Toys',
        rescue: 'Rescue',
        pet_parenting: 'Pet Parenting',
        lifestyle: 'Lifestyle',
        dog: 'Dog',
        cat: 'Cat',
        bird: 'Bird',
    },
};

const ACTIVITY_LOG_TYPES = {
    error_types: {
        /** AUTH */
        social_login_failed: 'social_login_failed',
        user_register_failed: 'user_register_failed',
        login_failed: 'login_failed',
        logout_failed: 'logout_failed',
        forgot_password_failed: 'forgot_password_failed',
        reset_password_failed: 'reset_password_failed',
        change_password_failed: 'change_password_failed',
        /** BOOKMARK */
        blog_bookmark_failed: 'blog_bookmark_failed',
        event_bookmark_failed: 'event_bookmark_failed',
        pet_store_bookmark_failed: 'pet_store_bookmark_failed',
        /** FOLLOW */
        failed_to_follow_breeder: 'failed_to_follow_breeder',
        failed_to_follow_pet_influencer: 'failed_to_follow_pet_influencer',
        failed_to_follow_event: 'failed_to_follow_event',
        failed_to_follow_author: 'failed_to_follow_author',
        failed_to_follow_pet_store: 'failed_to_follow_pet_store',
        failed_to_follow_pet_startup: 'failed_to_follow_pet_startup',
        /** LIKE */
        puppy_like_failed: 'puppy_like_failed',
        psr_like_failed: 'psr_like_failed',
        blog_like_failed: 'blog_like_failed',
        pet_name_like_failed: 'pet_name_like_failed',
        failed_to_like: 'failed_to_like',
        /** BREEDER/AUTH */
        breeder_register_failed: 'breeder_register_failed',
        failed_to_add_mobile_no: 'failed_to_add_mobile_no',
        verify_otp: 'verify_otp',
        /** BREEDER */
        profile_not_found: 'profile_not_found',
        failed_to_save_breeder_info: 'failed_to_save_breeder_info',
        failed_to_save_kennel_info: 'failed_to_save_kennel_info',
        /** DOG */
        failed_to_add_dog: 'failed_to_add_dog',
        failed_to_add_n_update_dog: 'failed_to_add_n_update_dog',
        failed_to_fetch_dog_drop_down_filter: 'failed_to_fetch_dog_drop_down_filter',
        failed_to_update_dog: 'failed_to_update_dog',
        failed_to_manage_dog_status: 'failed_to_manage_dog_status',
        failed_to_delete_dog: 'failed_to_delete_dog',
        failed_to_delete_dog_file: 'failed_to_delete_dog_file',
        /** INVITE CUSTOMER */
        failed_to_send_invitation_for_review: 'failed_to_send_invitation_for_review',
        /** PUPPY */
        failed_add_n_update_puppy: 'failed_add_n_update_puppy',
        failed_to_update_about_puppy_parent: 'failed_to_update_about_puppy_parent',
        failed_to_manage_puppy_status: 'failed_to_manage_puppy_status',
        failed_update_puppy: 'failed_update_puppy',
        failed_puppy_delete: 'failed_puppy_delete',
        /** FILE */
        image_ext_not_valid: 'image_ext_not_valid',
        audio_ext_not_valid: 'audio_ext_not_valid',
        csv_ext_not_valid: 'csv_ext_not_valid',
        failed_compress_file_using_buffer: 'failed_compress_file_using_buffer',
        failed_sharp_compress: 'failed_sharp_compress',
        failed_compress_file: 'failed_compress_file',
        failed_to_save_file: 'failed_to_save_file',
        /** TOKEN */
        save_token_failed: 'save_token_failed',
        generate_auth_tokens_failed: 'generate_auth_tokens_failed',
    },
    success_types: {
        /** AUTH */
        social_login_success: 'social_login_success',
        user_register_success: 'user_register_success',
        login_success: 'login_success',
        logout_success: 'logout_success',
        email_send_success: 'email_send_success',
        reset_password_success: 'reset_password_success',
        /** BREEDER/AUTH */
        breeder_register_success: 'breeder_register_success',
        add_mobile_no_success: 'add_mobile_no_success',
        verify_otp_success: 'verify_otp_success',
        /** BREEDER */
        breeder_info_save_success: 'breeder_info_save_success',
        /** DOG */
        dog_create_success: 'dog_create_success',
        dog_info_save_success: 'dog_info_save_success',
        manage_dog_status_success: 'manage_dog_status_success',
        dog_delete_success: 'dog_delete_success',
        delete_dog_file_success: 'delete_dog_file_success',
        /** INVITE CUSTOMER */
        review_invitation_sent_success: 'review_invitation_sent_success',
        /** PUPPY */
        puppy_info_save_success: 'puppy_info_save_success',
        manage_puppy_status_success: 'manage_puppy_status_success',
        puppy_delete_success: 'puppy_delete_success',
        /** LIKE */
        like_success_to_puppy: 'like_success_to_puppy',
        like_success_to_shelter_rescue: 'like_success_to_shelter_rescue',
        like_success_to_blog: 'like_success_to_blog',
        like_success_to_pet_name: 'like_success_to_pet_name',
        /** REMOVE LIKE */
        remove_like_success_to_puppy: 'remove_like_success_to_puppy',
        remove_like_success_to_shelter_rescue: 'remove_like_success_to_shelter_rescue',
        remove_like_success_to_blog: 'remove_like_success_to_blog',
        remove_like_success_to_pet_name: 'remove_like_success_to_pet_name',
        /** FOLLOW */
        follow_success_to_breeder: 'follow_success_to_breeder',
        follow_success_to_pet_influencer: 'follow_success_to_pet_influencer',
        follow_success_to_event: 'follow_success_to_event',
        follow_success_to_author: 'follow_success_to_author',
        follow_success_to_pet_store: 'follow_success_to_pet_store',
        follow_success_to_pet_startup: 'follow_success_to_pet_startup',
        /** UNFOLLOW */
        unfollow_success_to_breeder: 'unfollow_success_to_breeder',
        unfollow_success_to_pet_influencer: 'unfollow_success_to_pet_influencer',
        unfollow_success_to_event: 'unfollow_success_to_event',
        unfollow_success_to_author: 'unfollow_success_to_author',
        unfollow_success_to_pet_store: 'unfollow_success_to_pet_store',
        unfollow_success_to_pet_startup: 'unfollow_success_to_pet_startup',
    },
    type: {
        success: ' Success',
        fail: 'Fail',
    },
};

const USER_FROM = {
    WEB: 'Web',
    APP: 'App',
};

const DEVICE_TYPE = {
    ANDROID: 'Android',
    IOS: 'iOS',
};

const VERSION_TYPES = {
    config: 'config',
    ios: 'iOS',
    android: 'android',
};

const Predefine_Types = {
    Vaccine: 'vaccine',
    Deworming_Reminder: 'deworming_reminder',
    Expense_Category: 'expense_category',
    Grooming_Reminder: 'grooming_reminder',
};

const Meal_Category = {
    Breakfast: 'Breakfast',
    Lunch: 'Lunch',
    Dinner: 'Dinner',
};

const WALK_ADD_TYPE = {
    static: 'static',
    dynamic: 'dynamic',
};

const Reminder_Category = {
    Vaccine: 'Vaccine',
    Deworming: 'Deworming',
    Grooming: 'Grooming',
    Meals: 'Meals',
};
const PET_STARTUP = {
    STATUS: {
        active: 'Active',
        inactive: 'Inactive',
    },
    COMPANY_TYPE: {
        B2B: 'B2B',
        B2C: 'B2C',
        B2B2C: 'B2B2C',
    },
    FUND_SERIES: {
        bootstrapped: 'Bootstrapped',
        angel_round: 'Angel round',
        pre_seed: 'Pre - seed',
        seed_funding: 'Seed funding',
        series_a: 'Series A',
        series_b: 'Series B',
        series_c: 'Series C',
        undisclosed: 'Undisclosed',
    },
    COMPANY_SIZE: {
        two_to_ten: '2 - 10',
        eleven_to_fifty: '11 - 50',
        fifty_one_to_two_hun: '51 - 200',
        two_hun_one_to_five_hun: '201 - 500',
        five_hun_plus: '500+',
    },
    CATEGORY: {
        pet_supplies: 'Pet supplies',
        pet_services: 'Pet services',
        tech_products: 'Tech products',
        e_commerce: 'E-commerce',
        others: 'Others',
    },
};

const PREDEFINED_VALUE_TYPE = {
    pet_startup_specialization: 'pet-startup-specialization',
    pet_influencer_work_with_me: 'pet-influencer-work-with-me',
    knowledge_center_topic: 'knowledge-center-topic',
};

const APP_TYPES = {
    parentsPet: 'pet_parent_app',
    breeder: 'breeder_app',
};

const KNOWLEDGE_CENTER = {
    CATEGORY: {
        breeder_help: 'Breeder Help',
        stores: 'Stores',
        events: 'Events',
        influencer: 'Influencer',
        pet_startups: 'Pet Startups',
        shelters: 'Shelters',
    },
};

const ARTICLE_HELPFUL = {
    helpful: 'helpful',
    not_helpful: 'not_helpful',
};

const QUICK_SEARCH_HELP = {
    getting_started: 'Getting Started',
    dogs: 'Dogs',
    listing_puppies: 'Listing Puppies',
    speak_at_the_event: 'Speak at the event',
    all_about_dogs: 'All about Dogs',
    cats: 'Cats',
    contact_breeder: 'Contact Breeder',
    donate_for_shelters: 'Donate for Shelters',
    gms: 'GMS',
    adopting_a_puppy: 'Adopting a puppy',
    active_breeds: 'Active Breeds',
    stores: 'Stores',
};

const LANDING_PAGES = {
    breeder_landing_page: 'breeder_landing_page',
};

const IMAGE_ORIENTATION = {
    horizontal: 'horizontal',
    vertical: 'vertical',
    square: 'square',
};

const HEADER_TYPE = {
    dogs: 'dogs',
    cats: 'cats',
    fish: 'fish',
    birds: 'birds',
    directory: 'directory',
    news_and_stories: 'news_and_stories',
    event: 'events',
    shelters_and_rescue: 'shelters_and_rescue',
};

const BROADCAST_NOTIFICATION = {
    BREEDER_APP: {
        TYPES: {
            complete_breeder_profile: 'complete_breeder_profile',
            complete_kennel_profile: 'complete_kennel_profile',
            add_your_dog: 'add_dog',
            add_first_puppy: 'add_first_puppy',
            update_kennel_banner: 'update_kennel_banner',
            all_breeders: 'all_breeders',
            upload_certificate_later: 'upload_certificate_later',
        },
    },
    PET_PARENT_APP: {
        TYPES: {
            all_users: 'all_users',
            user_with_one_pet: 'user_with_one_pet',
            user_with_multi_peet: 'user_with_multi_peet',
        },
    },
};

const BANNER_TYPE = {
    TYPES: {
        onboard: 'onboard',
        home_landing_page: 'home_landing_page',
        event_landing_page: 'event_landing_page',
        pet_startup_landing_page: 'pet_startup_landing_page',
    },
    FILTER_TYPES: {
        onboard: 'onboard',
        landing_pages: 'landing_pages',
    },
};

const KENNEL_PHOTO_TYPE = {
    show_of_image: 'show_of_image',
    banner: 'banner',
};

const SCHEDULER = {
    FREQUENCY: {
        every_day: 'every_day',
        once_a_week: 'once_a_week',
        once_a_two_week: 'once_a_two_week',
        once_a_month: 'once_a_month',
    },
    SCHEDULER_TYPE: {
        update_your_banner: 'update_your_banner',
        complete_your_profile: 'complete_your_profile',
    },
};

const REQUEST_STATUS = {
    pending: 'pending',
    accept: 'accept',
    reject: 'reject',
};

const MESSAGE_TYPE = {
    unread: 'unread',
    read: 'read',
    pending: 'pending',
};

const KENNEL_CERTIFICATE_STATUS = {
    approve: 'Approve',
    reject: 'Reject',
    pending: 'Pending',
};

const NOTIFICATION_PET_PARENT_TYPE = {
    connect_explore: 'connect_explore',
    connect_messages: 'connect_messages',
    connect_requests: 'connect_requests',
    accept_request: 'accept_request',
    pet_diary: 'pet_diary',
    news_and_stories: 'news_and_stories',
};
const AUTO_NOTIFICATIONS = {
    TYPES: {
        walking_section: 'walking_section',
        meals_section: 'meals_section',
        pet_details: 'pet_details', //! petId is required from Mobile side for redirection
        edit_pet_profile: 'edit_pet_profile', //! petId is required from Mobile side for redirection
    },
    TOPICS: {
        /** Topics for "Walking Section" */
        adventure_awaits: 'adventure_awaits',
        ready_set_woof: 'ready_set_woof',
        walk_time_fun: 'walk_time_fun',
        sniffari_expedition: 'sniffari_expedition',
        rock_the_walk: 'rock_the_walk',
        refresh_n_revitalize: 'refresh_n_revitalize',
        walk_tastic_journey_for_your_dogs: 'walk_tastic_journey_for_your_dogs',
        /** Topics for "Meal Section" */
        feast_reminder_for_your_dogs: 'feast_reminder_for_your_dogs',
        chef_time_for_your_dogs: 'chef_time_for_your_dogs',
        track_your_dog_treats: 'track_your_dog_treats',
        log_those_full_tummies: 'log_those_full_tummies',
        whats_on_your_dogs_menu: 'whats_on_your_dogs_menu',
        happy_meal_time_for_your_dogs: 'happy_meal_time_for_your_dogs',
        paws_up_log_your_dogs_meals: 'paws_up_log_your_dogs_meals',
        /** Topics for "Pet Birthday" */
        pet_birthday: 'pet_birthday',
    },
};

const FIREBASE = {
    /**
     * Initialize application variable name
     * [Note: Please don't modify exists APPS items.]
     */
    APPS: {
        happyPetApp: 'happyPetApp',
        ppaApp: 'ppaApp',
    },
};

const PET_NAME = {
    THEME: {
        adventure_and_travel: 'Adventure and Travel',
        bollywood: 'Bollywood',
        colors_and_gems: 'Colors and Gems',
        culinary: 'Culinary',
        desi: 'Desi',
        fairy_tales_and_fantasy: 'Fairy Tales and Fantasy',
        mythical_creatures: 'Mythical Creatures',
        space_and_astronomy: 'Space and Astronomy',
        superheroes_and_villains: 'Superheroes and Villains',
    },
    SUITABLE_FOR: {
        dog: 'Dog',
        cat: 'Cat',
        bird: 'Bird',
    },
    GENDER: {
        male: 'Male',
        female: 'Female',
    },
};

const CONVERSATION_STATUS = {
    removed: 'removed',
    connected: 'connected',
    rejected: 'rejected',
    pending: 'pending',
    deleted: 'deleted',
};

const ACTION_MESSAGE = {
    start_conversation: 'Start Conversation',
    remove_connection: 'Connection Removed',
    request_accepted: 'Request Accepted',
    request_ignored: 'Request Ignored',
    delete_account: 'This pet parent has deactivated their account',
};

const DELETE_ACCOUNT_USER = {
    delete_account_user_first_name: 'User Unavailable',
    delete_account_user_last_name: '',
    delete_account_user_image:
        'https://happypetproduction.s3.ap-south-1.amazonaws.com/petParentHomeImages/user_not_exist_or_remove.webp',
};

const REMOVE_CONNECTION_USER = {
    remove_connection_user_first_name: 'User Unavailable',
    remove_connection_user_last_name: '',
};

const CTA_TYPE = {
    link: 'link',
    action: 'action',
};

module.exports = {
    BREEDER_BEHAVIOUR_TYPE,
    BREED_BEHAVIOUR_TYPE,
    DOG_PREDEFINED,
    FILES_FOLDER,
    FILE_QUALITY,
    ENQUIRY,
    PET_TYPE,
    ROLES,
    SOCIAL_TYPES,
    TOKEN_TYPES,
    SOCKET_EVENT_TYPE,
    BLOG_TOPICS,
    GENDER,
    LANGUAGE,
    CAT_PREDEFINED,
    LIFE_TIME_PERIOD,
    MAINTENANCE,
    IDEAL_SPACE,
    WEATHER_TYPE,
    TIME_DURATION,
    ENERGY_LEVEL,
    BENEFITS_OF_GROOMING,
    SHEDDING,
    PUPPY_STATUS,
    // SERVICE_PROVIDED,
    KCI_REGISTRATION,
    PSR_ANIMALS,
    BLOG_PET_TYPES,
    PSR_PET_TYPES,
    NOTIFICATION_TYPES,
    EVENT_TYPES,
    MSG91_WHATSAPP_TEMPLATES_NAME,
    MSG91_WHATSAPP_CAMPAIGN_NAME,
    PET_STORE,
    HAPPY_PET_MODULES,
    NEWSLETTER,
    EVENT_FEE_TYPE,
    FISH_PREDEFINED,
    WEIGHT_TYPES,
    TIME_TYPES,
    TIME_OF_DAY,
    WALK_STATUS,
    MOTIVATIONS,
    PET_INFLUENCER,
    ACTIVITY_LOG_TYPES,
    USER_FROM,
    DEVICE_TYPE,
    VERSION_TYPES,
    Predefine_Types,
    ALL_BREED_SIZE,
    Meal_Category,
    WALK_ADD_TYPE,
    Reminder_Category,
    PET_STARTUP,
    PREDEFINED_VALUE_TYPE,
    APP_TYPES,
    KNOWLEDGE_CENTER,
    ARTICLE_HELPFUL,
    QUICK_SEARCH_HELP,
    LANDING_PAGES,
    AI_SENSY,
    IMAGE_ORIENTATION,
    BIRD_PREDEFINED,
    HEADER_TYPE,
    BROADCAST_NOTIFICATION,
    BANNER_TYPE,
    KENNEL_PHOTO_TYPE,
    SCHEDULER,
    REQUEST_STATUS,
    MESSAGE_TYPE,
    KENNEL_CERTIFICATE_STATUS,
    NOTIFICATION_PET_PARENT_TYPE,
    AUTO_NOTIFICATIONS,
    PET_NAME,
    FIREBASE,
    MESSAGE_ACTION_TYPE,
    CONVERSATION_STATUS,
    ACTION_MESSAGE,
    DELETE_ACCOUNT_USER,
    CTA_TYPE,
    REMOVE_CONNECTION_USER,
};
